//= require "lib/underscore"
//= require "lib/jquery-1.9.1.min.js"
//= require "lib/jquery.timeago"
//= require "lib/jquery.responsive_images"
//= require "lib/twitter_feed"
//= require "initializer"
