production:
  stack: cedar
  app: eurucamp-blog
  config: &default
    BUNDLE_WITHOUT: "development:test"
    BUILDPACK_URL: http://github.com/indirect/heroku-buildpack-middleman.git

staging:
  stack: cedar
  app: eurucamp-blog-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
    BUILDPACK_URL: http://github.com/indirect/heroku-buildpack-middleman.git
